# Generated by Django 2.2.6 on 2019-11-20 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitratoruser',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
