# Generated by Django 2.2.6 on 2019-12-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='vote_count',
        ),
    ]
