# Generated by Django 2.2.6 on 2019-11-26 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arbitratoruser',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
