# Generated by Django 2.2.7 on 2019-11-07 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arbitrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistic',
            new_name='ArbitratorUser',
        ),
    ]
