# Generated by Django 2.2.6 on 2019-12-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
