# Generated by Django 2.2.7 on 2019-11-10 06:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arbitrator', '0002_auto_20191107_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitratoruser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='arbitratoruser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='arbitratoruser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='arbitratoruser',
            name='user',
        ),
        migrations.AddField(
            model_name='arbitratoruser',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
