# Generated by Django 2.2.6 on 2019-12-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrator', '0002_poll_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='is_available',
            new_name='is_result_available',
        ),
        migrations.AddField(
            model_name='poll',
            name='is_vote_available',
            field=models.BooleanField(default=True),
        ),
    ]
