# Generated by Django 2.2.7 on 2019-11-10 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arbitrator', '0003_auto_20191110_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitratoruser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='arbitratoruser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='arbitratoruser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='arbitratoruser',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arbitratoruser',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
