# Generated by Django 2.2.6 on 2019-11-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrator', '0003_question_multiple_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitratoruser',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
