# Generated by Django 2.2.6 on 2019-12-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrator', '0004_textanswer_poll_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceanswer',
            name='value',
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='poll_submission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='arbitrator.PollSubmission'),
            preserve_default=False,
        ),
    ]
